version: "3.9"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Cuiaba
    volumes:
      - ./config:/config
      - ./media:/media
    ports:
      - ${PORT}:8096 # expondo de maneira local, através da 8096
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: "1000:1000"
    container_name: ${TUNNEL_NAME}_cloudflared
    command: tunnel --no-autoupdate --config /etc/cloudflared/${CONFIG_FILE} run ${TUNNEL_NAME}
    volumes:
      - /home/asafe-borges/.cloudflared:/etc/cloudflared
    restart: unless-stopped
