version: "3.9"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./config:/config
      - ./media:/media
    ports:
      - ${PORT}:32400 # expondo de maneira local, através da 32400
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: plex_cloudflared
    command: tunnel --no-autoupdate run ${TUNNEL_NAME}
    volumes:
      - /home/asafe-borges/.cloudflared:/etc/cloudflared
    restart: unless-stopped
